// GENERATED by scripts/gen-contracts.mjs from docs/05-spec-agent-runtime-policy.md mục 1 — DO NOT EDIT. Sửa nguồn rồi chạy lại.
import type { Ms } from '../domain/d3';
import type { SessionContext } from '../gateway/d4';

export interface AgentRuntime {
  id: string;                                   // 'claude-agent-sdk'
  authStatus(): Promise<{ ok: boolean; method: 'claude-plan' | 'chatgpt-plan' | 'api-key' | 'none'; detail?: string }>;
  openSession(opts: SessionOptions): Promise<AgentSession>;
}

export interface SessionOptions {
  kind: 'main' | 'frame' | 'producer' | 'critic' | 'ops';
  context: SessionContext;                      // D4 mục 2.2
  model: string;                                // theo bảng mục 2
  systemAppend: string;                         // quy tắc app (mục 6) + chỉ dẫn theo kind
  plugins: string[];                            // đường dẫn tuyệt đối thư mục plugin (mục 3)
  tools: ToolPolicy;                            // mục 4
  resume?: string;                              // id phiên để tiếp tục (chỉ 'main')
  maxTurns?: number; budgetTokens?: number;
  telemetry: { traceparent: string };           // D11
}

export interface AgentSession {
  id: string;
  readonly sdkSessionId?: string;               // id runtime; Codex dùng tiền tố codex: khi lưu qua fallback
  send(message: UserMessage): AsyncIterable<AgentEvent>;
  interrupt(): Promise<void>;
  close(): Promise<void>;
}

export type UserMessage = { text: string; attachments?: { path: string; mime: string }[]; context_refs?: ContextRef[] };
export type ContextRef = { kind: 'frame' | 'time' | 'element' | 'caption_group'; id?: string; time_ms?: Ms };

export type AgentEvent =
  | { type: 'text_delta'; text: string }
  | { type: 'tool_call'; id: string; name: string; input: unknown }
  | { type: 'tool_result'; id: string; ok: boolean; summary: string }
  | { type: 'usage'; input_tokens: number; output_tokens: number; cost_usd?: number }
  | { type: 'done'; stop_reason: string }
  | { type: 'error'; code: string; message: string };

export type ToolPolicy = { allowed: string[]; readRoots: string[] };   // allowed: tên tool MCP + built-in theo mục 4; readRoots: thư mục cho Read/Glob/Grep
