// GENERATED by scripts/gen-contracts.mjs from docs/06-spec-workflow-skill.md — DO NOT EDIT. Sửa nguồn rồi chạy lại.
import type { VideoId, AssetId, RelPath, Ms, Line, Scene, Frame, ManualDelta } from '../domain/d3';
import type { ConfigKey } from '../domain/config-keys';

export interface WorkflowManifest {
  id: string; version: string; title: string; description: string;
  app_api: string;                          // semver range
  upstream?: { hyperframes_workflow: string; hyperframes_version: string };
  output_profiles: string[];                // cho phép; phần tử đầu là mặc định
  requires: string[];                       // capability bắt buộc
  optional?: string[];
  brief?: { questions: string[] };          // câu hỏi thêm cho router khi chốt brief (mục 3.0)
  scripts?: { id: string; command: string; args_schema?: object; writes?: string[] }[];
  config_defaults?: Record<string, unknown>; // tầng cấu hình `workflow` (D3 mục 7.1): chỉ khóa cho phép ở tầng channel hoặc video
  steps: StepDecl[];                        // không gồm brief (brief là pha trước workflow)
}

export type StepLibraryId = 'design-system' | 'script' | 'storyboard' | 'cast' | 'voice' | 'assets' | 'frame-build'
  | 'animatic' | 'captions' | 'music' | 'look' | 'effects' | 'overlays' | 'finish' | 'lipsync' | 'finalize' | 'publish-meta' | 'render';

export interface StepDecl {
  id: string;                               // duy nhất trong workflow
  uses: StepLibraryId;
  title: string;
  after?: string[];                         // phụ thuộc; mặc định = bước trước
  params?: Record<string, unknown>;         // theo schema params của bước (mục 2)
  refine?: { enabled: boolean; rubric: string; min_rounds?: number; max_rounds?: number; threshold?: number };
  approval?: { required: boolean; summary_template?: string };
  gate?: GateDecl[];                        // thêm vào gate mặc định của bước
  skip_if?: { config: ConfigKey; equals: unknown } | { phase_before: 'M3' }; // điều kiện bỏ qua; ngữ pháp duy nhất
}

export type GateDecl =
  | { kind: 'artifact_valid'; path: string }
  | { kind: 'graph_fresh'; nodes: string }  // ví dụ 'audio.line:*'
  | { kind: 'approved'; step: string }
  | { kind: 'script'; script: string }      // script trả exit 0 = qua
  | { kind: 'objective'; check: string; params?: Record<string, unknown> };   // mục 4.2

export interface Rubric { id: string; version: number; scale: 10;
  criteria: { id: string; weight: number; prompt: string }[];   // Σ weight = 1
  severity_rules: string; }

export interface FramePacket {
  video_id: VideoId; frame: Frame; scene: Scene;
  lines: Line[]; timing: { start_ms: Ms; duration_ms: Ms };
  design_system: RelPath;                 // frame.md
  blueprint?: { id: string; path: RelPath; vars: Record<string, string> };
  assets: { asset_id: AssetId; file: RelPath; width: number; height: number; alpha: boolean }[];
  output_path: RelPath;                   // compositions/frames/<fr>.html — phạm vi ghi duy nhất
  rules: string[];                        // từ hồ sơ kênh: font, màu, vùng an toàn…
  pinned_delta?: ManualDelta;             // khi sinh lại có áp lại chỉnh tay
}
