// GENERATED by scripts/gen-contracts.mjs from docs/03-spec-domain-artifacts.md mục 3–7 — DO NOT EDIT. Sửa nguồn rồi chạy lại.
import type { ConfigKey } from './config-keys';

export type Id<P extends string> = `${P}_${string}`;
export type ChannelId = Id<'ch'>; export type VideoId = Id<'vd'>; export type BeatId = Id<'bt'>;
export type SceneId = Id<'sc'>; export type FrameId = Id<'fr'>; export type ElementId = Id<'el'>;
export type LineId = Id<'ln'>; export type CaptionGroupId = Id<'cg'>; export type CastId = Id<'ca'>;
export type VoiceId = Id<'vo'>; export type AssetId = Id<'as'>; export type MusicTrackId = Id<'mt'>;

export type RelPath = string;          // đường dẫn tương đối, '/'
export type JobId = Id<'jb'>; export type RenderId = Id<'rd'>; export type ApprovalId = Id<'ap'>; export type SessionId = Id<'ss'>;
export type Iso8601 = string;          // '2026-10-03T10:49:00+07:00'
export type Ms = number;               // mili giây, số nguyên
export type Lang = 'vi' | 'de' | 'en';
export type Sha256 = string;           // hex 64 ký tự

export interface Versioned { schema_version: number; }

export interface Beat {            // khai báo trong SCRIPT.md
  id: BeatId; order: number; title: string;
  line_ids: LineId[];
}

export interface Line {            // khai báo trong SCRIPT.md
  id: LineId; beat_id: BeatId; order: number;
  speaker: 'narrator' | CastId;
  text: string;             // chữ hiển thị/caption
  tts_text?: string;        // chữ đã chuẩn hóa cho TTS (số, viết tắt) nếu khác text
  direction?: string;       // chỉ dẫn diễn xuất, ví dụ "chậm, trầm"
  emotion?: string;         // khóa biến thể cảm xúc của giọng
  pause_after_ms?: Ms;
}

export interface Scene {           // khai báo trong STORYBOARD.md
  id: SceneId; order: number; title: string;
  setting?: string; time_of_day?: string; mood?: string;
  look?: string;            // khóa look trong hồ sơ kênh
  music?: 'none' | { track_id?: MusicTrackId; query?: string; volume_db?: number };
  frame_ids: FrameId[];
  config?: Record<string, unknown>;   // ghi đè cấu hình tầng scene
}

export interface Frame {           // khai báo trong STORYBOARD.md
  id: FrameId; scene_id: SceneId; order: number;
  beat_ids: BeatId[];       // Beat–Frame nhiều–nhiều
  line_ids: LineId[];       // line phát trong frame; mỗi line thuộc ĐÚNG MỘT frame (thời lượng frame suy từ audio)
  blueprint?: string;       // id blueprint (D13)
  intent: string;           // mô tả ý đồ hình ảnh/chuyển động
  layers: Layer[];
  transition_in?: { type: string; duration_ms: Ms };
  effects?: string[];       // id media effect
  overlays?: { block: string; vars: Record<string, string> }[];
  lipsync?: { cast_id: CastId; mouth_anchor: ElementId };
  sfx?: { track_id: MusicTrackId; at_ms: Ms; volume_db?: number }[];   // at_ms tương đối đầu frame (D8)
  min_duration_ms?: Ms;     // khi frame không có line
  config?: Record<string, unknown>;
}

export interface Layer {
  id: ElementId;
  kind: 'background' | 'image' | 'object' | 'text' | 'shape' | 'chart' | 'overlay' | 'mouth';
  asset_id?: AssetId;       // ảnh/vật thể
  asset_request?: AssetRequest;  // khi chưa có asset: mô tả để bước assets xử lý
  text?: string;
  notes?: string;
}

export interface AssetRequest {
  source: 'library' | 'code' | 'generate' | 'user';
  prompt?: string; reference_asset_ids?: AssetId[];
  transparent?: boolean; aspect?: '16:9' | '9:16' | '1:1' | '4:3';
}

export interface CastMember {      // CAST.md (video) hoặc characters/<id>/cast.json (kênh)
  id: CastId; name: string; role: 'narrator' | 'character';
  voice_id: VoiceId; emotions?: Record<string, RelPath>;   // khóa → ref audio
  reference_images: AssetId[];
  expressions?: Record<string, AssetId>;   // file ở characters/<cast_id>/expressions/<key>.png, đăng ký trong assets/manifest.json của kênh
  mouth_set?: string;                      // file: mouths/<set>/<view>/<state>.svg, view ∈ front|three_quarter, state ∈ closed|half|open
  mouth_anchor?: { x: number; y: number; scale: number };
  caption_color?: string;   // hex
}

export interface OutputProfile {   // extensions/outputs/<id>/output.json
  id: string; width: number; height: number; fps: number;
  safe_area: { top: number; right: number; bottom: number; left: number }; // tỉ lệ 0–1
  max_duration_ms?: Ms;
  video: { codec: 'h264'; crf: number }; audio: { codec: 'aac'; sample_rate: 48000; loudness_lufs: number };
}

export interface AudioMeta extends Versioned {
  video_id: VideoId; sample_rate: 48000;
  lines: {
    line_id: LineId; file: RelPath;            // audio/lines/<line_id>.wav
    start_ms: Ms; duration_ms: Ms;             // vị trí trên **chuỗi lời đọc** (các line nối theo thứ tự SCRIPT + pause_after_ms), không tính frame không lời; mốc tuyệt đối trên video do nút frame_timing tính (D4 mục 8)
    speaker: 'narrator' | CastId; voice_id: VoiceId;
    words: { i: number; text: string; start_ms: Ms; end_ms: Ms; conf?: number }[]; // tương đối với đầu line
    asr_wer?: number; asr_flag?: 'ok' | 'mismatch' | 'accepted';   // accepted = người dùng chấp nhận dù lệch; asr_regen_count?: number
    content_hash: Sha256;                      // hash đầu vào sinh audio (D4 cache key)
  }[];
  total_duration_ms: Ms;
}

export interface CaptionGroups extends Versioned {
  video_id: VideoId; style: string;            // id thành phần caption catalog
  groups: { id: CaptionGroupId; line_id: LineId; word_range: [number, number]; // [đầu, cuối] chỉ số word, gồm cả hai đầu
            text: string; start_ms: Ms; end_ms: Ms; emphasis?: number[]; speaker?: string }[];
}

export interface CaptionOverrides extends Versioned {
  video_id: VideoId;
  style?: { component?: string; vars?: Record<string, string> };    // từ Studio
  groups: Record<CaptionGroupId, {
    start_ms?: Ms; end_ms?: Ms; text?: string;                    // từ bảng caption
  }>;
  splits: { group_id: CaptionGroupId; at_word: number; new_id: CaptionGroupId }[];
  merges: { group_ids: CaptionGroupId[]; new_id: CaptionGroupId }[];
}

export interface LipsyncCues extends Versioned {
  line_id: LineId; cast_id: CastId; fps: number;
  cues: { frame: number; mouth: 'closed' | 'half' | 'open' }[];   // video frame tương đối đầu line
}

export interface VideoState extends Versioned {
  video_id: VideoId; channel_id: ChannelId;
  created_at: Iso8601; updated_at: Iso8601;
  phase: 'briefing' | 'workflow';           // briefing: chưa chọn workflow (D6 mục 3.0)
  workflow: { id: string; version: string } | null;   // nguồn chính thức; null khi briefing
  output_profile: string | null;            // nguồn chính thức (khóa output.profile tầng video đọc từ đây)
  read_only_videos?: VideoId[];             // video khác được đọc (shorts từ video dài)
  owner: 'agent' | 'studio';                 // chủ sửa file cảnh hiện tại
  owner_since?: Iso8601;
  steps: Record<string, StepState>;          // khóa = step id trong manifest
  approvals: Approval[];
  pinned_frames: Record<FrameId, ManualDelta>;
  config_overrides: Record<string, unknown>; // tầng video (mục 7)
  budget: { tokens_used: number; api_cost_usd: number; limits?: { tokens?: number; api_cost_usd?: number } };
}

export interface StepState {
  status: 'pending' | 'running' | 'waiting_approval' | 'done' | 'failed' | 'skipped' | 'stale';
  started_at?: Iso8601; finished_at?: Iso8601;
  attempt: number; error?: { code: string; message: string };
  outputs?: RelPath[];
  refine?: { rounds: number; final_score?: number; incomplete?: boolean };
  waived?: string[];                       // 043: kiểm mềm (objective `audio_duration`) người dùng chấp nhận bỏ qua; mất khi chạy lại bước
}

export interface Approval {
  id: ApprovalId; step_id: string; status: 'pending' | 'approved' | 'changes_requested';
  requested_at: Iso8601; decided_at?: Iso8601; note?: string;
  artifact_hashes: Record<RelPath, Sha256>;   // nội dung đã duyệt; đổi hash → duyệt mất hiệu lực
}

export interface ManualDelta {
  pinned_at: Iso8601; base_hash: Sha256;      // hash HTML frame do agent sinh trước khi chỉnh tay
  changes: { element_id: ElementId | '*'; attr: string; before: string | null; after: string | null }[];   // '*' = nhận cả frame (D9 mục 3.4 c)
}

export interface ReviewRound extends Versioned {
  step_id: string; round: number; artifact: RelPath; draft_hash: Sha256;
  producer: { provider: string; model: string };
  critic: { provider: string; model: string };
  objective_checks: { id: string; pass: boolean; detail?: string }[];
  score: number;                             // 0–10
  criteria: { id: string; score: number; weight: number; note?: string }[];
  issues: { severity: 'critical' | 'major' | 'minor'; location?: string; text: string; fixed_in_round?: number }[];
  tokens: { input: number; output: number }; cost_usd: number; created_at: Iso8601;
}

export interface Provenance extends Versioned {
  output: RelPath; output_hash: Sha256;      // file tên provenance/<12 ký tự đầu output_hash>.json
  capability: string; provider: string; provider_version: string;
  model?: { id: string; file_hash?: Sha256 };
  params: Record<string, unknown>; seed?: number;
  inputs: { path?: RelPath; hash: Sha256; role: string }[];
  cache_key: Sha256; from_cache: boolean;
  source?: { kind: 'generated' | 'user_import' | 'library'; url?: string; attribution?: string };
  job_id?: string; created_at: Iso8601;
}

export interface AssetManifest extends Versioned {
  assets: { id: AssetId; file: RelPath; kind: 'image' | 'video' | 'svg' | 'audio';
            width?: number; height?: number; alpha?: boolean; tags: string[];
            description?: string; source: Provenance['source']; hash: Sha256; created_at: Iso8601 }[];
}

export interface RenderRecord extends Versioned {
  id: RenderId; mode: 'animatic' | 'draft' | 'release'; output_profile: string;
  started_at: Iso8601; finished_at?: Iso8601; status: 'running' | 'done' | 'failed' | 'canceled';
  file?: RelPath; duration_ms?: Ms; gate_results: { gate: string; pass: boolean; detail?: string }[];
  index_hash: Sha256;
}

export interface ChannelConfig extends Versioned {
  id: ChannelId; name: string; language: Lang; created_at: Iso8601;
  profile_dir: 'profile';
  config: Partial<Record<ConfigKey, unknown>>;     // tầng channel, ví dụ { "voice.id": "vo_…", "look.id": "warm-archive" }
}

export interface SettingsConfig extends Versioned {
  config: Partial<Record<ConfigKey, unknown>>;     // tầng app (mặc định của người dùng; thiếu khóa → mặc định trong bảng 7.2)
  installed: { profile: 'minimal' | 'standard' | 'full'; components: { id: string; version: string; installed_at: Iso8601; license_accepted?: string }[] };   // license_accepted: id giấy phép người dùng đã xác nhận (018)
  provider_fallbacks: Partial<Record<string, string[]>>;   // capability → danh sách provider id theo thứ tự
  provider_settings?: Partial<Record<string, Record<string, unknown>>>;   // cấu hình riêng provider không bí mật (ví dụ endpoint workspace của `image.qwen20-api`, 018)
  network: { allow: string[] };                    // domain cho phép (D5 mục 5.3)
  pricing: { provider: string; model: string; unit: 'mtok_in' | 'mtok_out' | 'image' | 'second'; usd: number }[];
  trace: { capture_content: boolean; retention_days: number; phoenix_enabled: boolean };   // mặc định true / 30 / false
  recent_channels: { path: string; opened_at: Iso8601 }[];
}

export interface ResolvedValue<T> { value: T; source: 'default' | 'app' | 'channel' | 'video' | 'scene' | 'frame'; path: string; }
export declare function resolveConfig<T>(key: ConfigKey, scope: { channel: ChannelId; video?: VideoId; scene?: SceneId; frame?: FrameId }): ResolvedValue<T>;
