// GENERATED by scripts/gen-contracts.mjs from docs/contracts/domain/*.ts — DO NOT EDIT. Sửa nguồn rồi chạy lại.

export type Id<P extends string> = `${P}_${string}`;
export type ChannelId = Id<'ch'>; export type VideoId = Id<'vd'>; export type BeatId = Id<'bt'>;
export type SceneId = Id<'sc'>; export type FrameId = Id<'fr'>; export type ElementId = Id<'el'>;
export type LineId = Id<'ln'>; export type CaptionGroupId = Id<'cg'>; export type CastId = Id<'ca'>;
export type VoiceId = Id<'vo'>; export type AssetId = Id<'as'>; export type MusicTrackId = Id<'mt'>;

export type RelPath = string;          // đường dẫn tương đối, '/'
export type JobId = Id<'jb'>; export type RenderId = Id<'rd'>; export type ApprovalId = Id<'ap'>; export type SessionId = Id<'ss'>; export type PlanItemId = Id<'pi'>;
export type Iso8601 = string;          // '2026-10-03T10:49:00+07:00'
export type Ms = number;               // mili giây, số nguyên
export type Lang = 'vi' | 'de' | 'en';
export type Sha256 = string;           // hex 64 ký tự

export interface Versioned { schema_version: number; }

export interface Beat {            // khai báo trong SCRIPT.md
  id: BeatId; order: number; title: string;
  line_ids: LineId[];
}

export interface Line {            // khai báo trong SCRIPT.md
  id: LineId; beat_id: BeatId; order: number;
  speaker: 'narrator' | CastId;
  text: string;             // chữ hiển thị/caption
  tts_text?: string;        // chữ đã chuẩn hóa cho TTS (số, viết tắt) nếu khác text
  direction?: string;       // chỉ dẫn diễn xuất, ví dụ "chậm, trầm"
  emotion?: string;         // khóa biến thể cảm xúc của giọng
  pause_after_ms?: Ms;
}

export interface Scene {           // khai báo trong STORYBOARD.md
  id: SceneId; order: number; title: string;
  setting?: string; time_of_day?: string; mood?: string;
  look?: string;            // khóa look trong hồ sơ kênh
  music?: 'none' | { track_id?: MusicTrackId; query?: string; volume_db?: number };
  frame_ids: FrameId[];
  config?: Record<string, unknown>;   // ghi đè cấu hình tầng scene
}

export interface Frame {           // khai báo trong STORYBOARD.md
  id: FrameId; scene_id: SceneId; order: number;
  beat_ids: BeatId[];       // Beat–Frame nhiều–nhiều
  line_ids: LineId[];       // line phát trong frame; mỗi line thuộc ĐÚNG MỘT frame (thời lượng frame suy từ audio)
  blueprint?: string;       // id blueprint (D13)
  intent: string;           // mô tả ý đồ hình ảnh/chuyển động
  layers: Layer[];
  transition_in?: { type: string; duration_ms: Ms };
  effects?: string[];       // id media effect
  overlays?: { block: string; vars: Record<string, string> }[];
  lipsync?: { cast_id: CastId; mouth_anchor: ElementId };
  sfx?: { track_id: MusicTrackId; at_ms: Ms; volume_db?: number }[];   // at_ms tương đối đầu frame (D8)
  min_duration_ms?: Ms;     // khi frame không có line
  config?: Record<string, unknown>;
}

export interface Layer {
  id: ElementId;
  kind: 'background' | 'image' | 'object' | 'text' | 'shape' | 'chart' | 'overlay' | 'mouth';
  asset_id?: AssetId;       // ảnh/vật thể
  asset_request?: AssetRequest;  // khi chưa có asset: mô tả để bước assets xử lý
  text?: string;
  notes?: string;
}

export interface AssetRequest {
  source: 'library' | 'code' | 'generate' | 'user';
  prompt?: string; reference_asset_ids?: AssetId[];
  transparent?: boolean; aspect?: '16:9' | '9:16' | '1:1' | '4:3';
}

export interface CastMember {      // CAST.md (video) hoặc characters/<id>/cast.json (kênh)
  id: CastId; name: string; role: 'narrator' | 'character';
  voice_id: VoiceId; emotions?: Record<string, RelPath>;   // khóa → ref audio
  reference_images: AssetId[];
  expressions?: Record<string, AssetId>;   // file ở characters/<cast_id>/expressions/<key>.png, đăng ký trong assets/manifest.json của kênh
  mouth_set?: string;                      // file: mouths/<set>/<view>/<state>.svg, view ∈ front|three_quarter, state ∈ closed|half|open
  mouth_anchor?: { x: number; y: number; scale: number };
  caption_color?: string;   // hex
}

export interface OutputProfile {   // extensions/outputs/<id>/output.json
  id: string; width: number; height: number; fps: number;
  safe_area: { top: number; right: number; bottom: number; left: number }; // tỉ lệ 0–1
  max_duration_ms?: Ms;
  video: { codec: 'h264'; crf: number }; audio: { codec: 'aac'; sample_rate: 48000; loudness_lufs: number };
}

export interface AudioMeta extends Versioned {
  video_id: VideoId; sample_rate: 48000;
  lines: {
    line_id: LineId; file: RelPath;            // audio/lines/<line_id>.wav
    start_ms: Ms; duration_ms: Ms;             // vị trí trên **chuỗi lời đọc** (các line nối theo thứ tự SCRIPT + pause_after_ms), không tính frame không lời; mốc tuyệt đối trên video do nút frame_timing tính (D4 mục 8)
    speaker: 'narrator' | CastId; voice_id: VoiceId;
    words: { i: number; text: string; start_ms: Ms; end_ms: Ms; conf?: number }[]; // tương đối với đầu line
    asr_wer?: number; asr_flag?: 'ok' | 'mismatch' | 'accepted';   // accepted = người dùng chấp nhận dù lệch; asr_regen_count?: number
    content_hash: Sha256;                      // hash đầu vào sinh audio (D4 cache key)
  }[];
  total_duration_ms: Ms;
}

export interface CaptionGroups extends Versioned {
  video_id: VideoId; style: string;            // id thành phần caption catalog
  groups: { id: CaptionGroupId; line_id: LineId; word_range: [number, number]; // [đầu, cuối] chỉ số word, gồm cả hai đầu
            text: string; start_ms: Ms; end_ms: Ms; emphasis?: number[]; speaker?: string }[];
}

export interface CaptionOverrides extends Versioned {
  video_id: VideoId;
  style?: { component?: string; vars?: Record<string, string> };    // từ Studio
  groups: Record<CaptionGroupId, {
    start_ms?: Ms; end_ms?: Ms; text?: string;                    // từ bảng caption
  }>;
  splits: { group_id: CaptionGroupId; at_word: number; new_id: CaptionGroupId }[];
  merges: { group_ids: CaptionGroupId[]; new_id: CaptionGroupId }[];
}

export interface LipsyncCues extends Versioned {
  line_id: LineId; cast_id: CastId; fps: number;
  cues: { frame: number; mouth: 'closed' | 'half' | 'open' }[];   // video frame tương đối đầu line
}

export interface VideoState extends Versioned {
  video_id: VideoId; channel_id: ChannelId;
  created_at: Iso8601; updated_at: Iso8601;
  phase: 'briefing' | 'workflow';           // briefing: chưa chọn workflow (D6 mục 3.0)
  workflow: { id: string; version: string } | null;   // nguồn chính thức; null khi briefing
  output_profile: string | null;            // nguồn chính thức (khóa output.profile tầng video đọc từ đây)
  read_only_videos?: VideoId[];             // video khác được đọc (shorts từ video dài)
  autopilot?: { plan_date: string; item_id: PlanItemId; channel_id: ChannelId };  // 052: video do Autopilot tạo theo mục kế hoạch ngày (đánh dấu để áp cổng chất lượng tự động; video làm tay không có trường này)
  owner: 'agent' | 'studio';                 // chủ sửa file cảnh hiện tại
  owner_since?: Iso8601;
  steps: Record<string, StepState>;          // khóa = step id trong manifest
  approvals: Approval[];
  pinned_frames: Record<FrameId, ManualDelta>;
  config_overrides: Record<string, unknown>; // tầng video (mục 7)
  budget: { tokens_used: number; api_cost_usd: number; limits?: { tokens?: number; api_cost_usd?: number } };
}

export interface StepState {
  status: 'pending' | 'running' | 'waiting_approval' | 'done' | 'failed' | 'skipped' | 'stale';
  started_at?: Iso8601; finished_at?: Iso8601;
  attempt: number; error?: { code: string; message: string };
  outputs?: RelPath[];
  refine?: { rounds: number; final_score?: number; incomplete?: boolean };
  waived?: string[];                       // 043: kiểm mềm (objective `audio_duration`) người dùng chấp nhận bỏ qua; mất khi chạy lại bước
}

export interface Approval {
  id: ApprovalId; step_id: string; status: 'pending' | 'approved' | 'changes_requested';
  requested_at: Iso8601; decided_at?: Iso8601; note?: string;
  artifact_hashes: Record<RelPath, Sha256>;   // nội dung đã duyệt; đổi hash → duyệt mất hiệu lực
}

export interface ManualDelta {
  pinned_at: Iso8601; base_hash: Sha256;      // hash HTML frame do agent sinh trước khi chỉnh tay
  changes: { element_id: ElementId | '*'; attr: string; before: string | null; after: string | null }[];   // '*' = nhận cả frame (D9 mục 3.4 c)
}

export interface ReviewRound extends Versioned {
  step_id: string; round: number; artifact: RelPath; draft_hash: Sha256;
  producer: { provider: string; model: string };
  critic: { provider: string; model: string };
  objective_checks: { id: string; pass: boolean; detail?: string }[];
  score: number;                             // 0–10
  criteria: { id: string; score: number; weight: number; note?: string }[];
  issues: { severity: 'critical' | 'major' | 'minor'; location?: string; text: string; fixed_in_round?: number }[];
  tokens: { input: number; output: number }; cost_usd: number; created_at: Iso8601;
}

export interface Provenance extends Versioned {
  output: RelPath; output_hash: Sha256;      // file tên provenance/<12 ký tự đầu output_hash>.json
  capability: string; provider: string; provider_version: string;
  model?: { id: string; file_hash?: Sha256 };
  params: Record<string, unknown>; seed?: number;
  inputs: { path?: RelPath; hash: Sha256; role: string }[];
  cache_key: Sha256; from_cache: boolean;
  source?: { kind: 'generated' | 'user_import' | 'library'; url?: string; attribution?: string };
  job_id?: string; created_at: Iso8601;
}

export interface AssetManifest extends Versioned {
  assets: { id: AssetId; file: RelPath; kind: 'image' | 'video' | 'svg' | 'audio';
            width?: number; height?: number; alpha?: boolean; tags: string[];
            description?: string; source: Provenance['source']; hash: Sha256; created_at: Iso8601 }[];
}

export interface RenderRecord extends Versioned {
  id: RenderId; mode: 'animatic' | 'draft' | 'release'; output_profile: string;
  started_at: Iso8601; finished_at?: Iso8601; status: 'running' | 'done' | 'failed' | 'canceled';
  file?: RelPath; duration_ms?: Ms; gate_results: { gate: string; pass: boolean; detail?: string }[];
  index_hash: Sha256;
}

export interface ResearchDoc extends Versioned {
  channel_id: ChannelId;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  date: string;                                    // YYYY-MM-DD theo `publish.timezone`
  generated_at: Iso8601;
  quota_units: number;                             // đơn vị quota YouTube Data API v3 đã dùng
  sources: {
    competitors: { channel_id: string; title?: string; videos: number; error?: ResearchSourceError }[];
    own_videos: number;                            // số video đã làm của kênh dùng để chấm độ mới
    trending: { region: string; videos: number; error?: ResearchSourceError };
    trends: { geo: string; items: number; error?: ResearchSourceError };
    news: { pillar: string; items: number; error?: ResearchSourceError }[];
  };
  candidates: ResearchCandidate[];                 // điểm cao trước
}
export interface ResearchSourceError { code: string; message: string; }
export interface ResearchCandidate {
  id: string;                                      // `yt:<video_id>` / `trend:<từ khóa>` / `news:<sha256-12 của link>`
  kind: 'competitor' | 'competitor_evergreen' | 'trending' | 'trend' | 'news';
  title: string; url?: string; source_channel?: { id: string; title: string };
  published_at?: Iso8601; pillar?: string;         // chủ đề trụ cột khớp nhất
  metrics?: { views?: number; likes?: number; comments?: number; duration_s?: number;
              outlier_ratio?: number; views_per_hour?: number; age_hours?: number;
              traffic?: number; similarity?: number };
  /** @minimum 0 @maximum 100 */
  score: number;
  reasons: string[];                               // tiếng Việt, mỗi tín hiệu một câu
}

export type PlanItemStatus = 'planned' | 'skipped' | 'in_production' | 'produced' | 'failed' | 'needs_review';
export interface DailyPlan extends Versioned {
  channel_id: ChannelId;
  /** @pattern ^\d{4}-\d{2}-\d{2}$ */
  date: string;                                    // YYYY-MM-DD theo `publish.timezone` của kênh
  generated_at: Iso8601;                           // lần lập/sửa gần nhất
  capacity: {
    videos: number;                                // số video khả thi của kênh hôm nay (050)
    limiting_factor: 'time' | 'tokens' | 'uploads' | 'cap';
    reasons: string[];                             // tiếng Việt (từ mô hình năng lực)
  };
  notes?: string[];                                // tiếng Việt: vì sao lập ít/không lập video (không đủ ứng viên, tạm dừng…)
  items: PlanItem[];
}
export interface PlanItem {
  id: PlanItemId;
  status: PlanItemStatus;
  candidate_id: string;                            // `ResearchCandidate.id` (5.17); chủ đề do người dùng/agent thêm tay dùng `manual:<id>`
  title: string;                                   // tên làm việc của video
  angle: string;                                   // một dòng: vì sao / góc nhìn (tiếng Việt)
  source: { kind: 'competitor' | 'competitor_evergreen' | 'trending' | 'trend' | 'news'; url?: string;
            source_channel?: { id: string; title: string } };
  workflow_id: string;
  output_profile: string;
  publish_at: Iso8601 | null;                      // có offset múi giờ; null = kênh không có khung giờ
  platforms: string[];                             // `publish.platforms` của kênh
  /** @minimum 0 @maximum 100 */
  score: number;                                   // điểm ứng viên (5.17)
  reasons: string[];                               // tiếng Việt
  video_id?: VideoId;                              // điền khi 052 tạo video
  note?: string;                                   // ghi chú của người dùng / lý do bỏ qua hoặc lỗi
}

export interface AutopilotLogLine {
  ts: Iso8601;
  level: 'info' | 'warn' | 'error';
  /** Mã sự kiện, ví dụ plan.built, item.start, gate.decision, step.retry, step.waive, limit.hit, item.parked, item.failed, item.produced, paid.allowed, item.reclaimed (052). */
  event: string;
  item_id?: PlanItemId;
  video_id?: VideoId;
  step_id?: string;
  message: string;                                 // tiếng Việt: việc gì + vì sao
  data?: Record<string, unknown>;                  // chi tiết máy đọc được (điểm, ngưỡng, thời điểm hết hạn mức…)
}

export interface ChannelConfig extends Versioned {
  id: ChannelId; name: string; language: Lang; created_at: Iso8601;
  profile_dir: 'profile';
  config: Partial<Record<ConfigKey, unknown>>;     // tầng channel, ví dụ { "voice.id": "vo_…", "look.id": "warm-archive" }
}

export interface SettingsConfig extends Versioned {
  config: Partial<Record<ConfigKey, unknown>>;     // tầng app (mặc định của người dùng; thiếu khóa → mặc định trong bảng 7.2)
  installed: { profile: 'minimal' | 'standard' | 'full'; components: { id: string; version: string; installed_at: Iso8601; license_accepted?: string }[] };   // license_accepted: id giấy phép người dùng đã xác nhận (018)
  provider_fallbacks: Partial<Record<string, string[]>>;   // capability → danh sách provider id theo thứ tự
  provider_settings?: Partial<Record<string, Record<string, unknown>>>;   // cấu hình riêng provider không bí mật (ví dụ endpoint workspace của `image.qwen20-api`, 018)
  network: { allow: string[] };                    // domain cho phép (D5 mục 5.3)
  pricing: { provider: string; model: string; unit: 'mtok_in' | 'mtok_out' | 'image' | 'second'; usd: number }[];
  trace: { capture_content: boolean; retention_days: number; phoenix_enabled: boolean };   // mặc định true / 30 / false
  recent_channels: { path: string; opened_at: Iso8601 }[];
  managed_channels?: { path: string; added_at: Iso8601 }[];   // kênh app quản lý (047, Autopilot M6); mở kênh lần đầu → thêm
}

export interface ResolvedValue<T> { value: T; source: 'default' | 'app' | 'channel' | 'video' | 'scene' | 'frame'; path: string; }
export declare function resolveConfig<T>(key: ConfigKey, scope: { channel: ChannelId; video?: VideoId; scene?: SceneId; frame?: FrameId }): ResolvedValue<T>;

// Front matter và mô hình đã parse của artifact Markdown (D3 mục 5.1–5.6, 5.15).
// D3 chỉ cho các phần này bằng ví dụ YAML/mô tả nên file này được viết tay, bám đúng ví dụ;
// mọi kiểu dùng lại từ d3.ts (sinh tự động). Xem specs/002-domain-artifacts/research.md R2.

export type DocStatus = 'draft' | 'approved';

/** D3 5.2 */
export interface BriefFrontMatter extends Versioned {
  video_id: VideoId;
  /** Đề xuất của router; null khi chưa đề xuất. */
  proposed_workflow: { id: string; version: string } | null;
  proposed_output_profile: string | null;
  source_video_id: VideoId | null;
  language: Lang;
  target_duration_ms: Ms | null;
  title_working: string;
  approved_at: Iso8601 | null;
}

/** D3 5.3 */
export interface FrameMdFrontMatter extends Versioned {
  generated_from: Sha256;
}

/** D3 5.3b */
export interface StoryFrontMatter extends Versioned {
  video_id: VideoId;
  status: DocStatus;
}

/** D3 5.3b — khối `sf-story` dưới mỗi heading `##`. */
export interface StoryBlock {
  title: string;
  summary: string;
  characters: string[];
  setting: string;
  beats: string[];
}

export interface StoryDoc {
  front: StoryFrontMatter;
  scenes: StoryBlock[];
}

/** D3 5.4 */
export interface ScriptFrontMatter extends Versioned {
  video_id: VideoId;
  language: Lang;
  status: DocStatus;
}

export interface ScriptDoc {
  front: ScriptFrontMatter;
  beats: Beat[];
  lines: Line[];
}

/** D3 5.5 */
export interface StoryboardFrontMatter extends Versioned {
  video_id: VideoId;
  status: DocStatus;
}

export interface StoryboardDoc {
  front: StoryboardFrontMatter;
  scenes: Scene[];
  frames: Frame[];
}

/** D3 5.6 — front matter của CAST.md (video). */
export interface CastFrontMatter extends Versioned {
  video_id: VideoId;
}

/** D3 5.6 — mục trong khối `sf-cast`: tham chiếu cast kênh theo `id`, có thể ghi đè trường. */
export type CastEntry = { id: CastId } & Partial<Omit<CastMember, 'id'>>;

export interface CastDoc {
  front: CastFrontMatter;
  cast: CastEntry[];
}

/** D3 5.15 */
export interface PublishFrontMatter extends Versioned {
  video_id: VideoId;
  title: string;
  tags: string[];
  chapters: { start_ms: Ms; title: string }[];
  status: DocStatus;
}

export type ConfigKey =
  | 'output.profile'
  | 'workflow.default'
  | 'voice.id'
  | 'voice.pause_after_ms'
  | 'look.id'
  | 'font.family'
  | 'caption.style'
  | 'caption.max_words'
  | 'overlay.rules'
  | `provider.${string}`
  | 'text.producer'
  | 'text.critic'
  | 'text.aux'
  | 'refine.min_rounds'
  | 'refine.max_rounds'
  | 'refine.threshold'
  | 'frame.min_duration_ms'
  | 'frame_build.parallel'
  | 'budget.tokens_per_video'
  | 'budget.api_cost_usd_per_video'
  | 'budget.cache_gb'
  | 'music.volume_db'
  | 'music.duck_db'
  | `asr.wer_threshold.${string}`
  | 'asr.max_regen'
  | 'lipsync.enabled'
  | 'workflow.autopilot'
  | 'workflow.key_approvals'
  | 'policy.auto_approve.batch_gen'
  | 'policy.auto_approve.paid_api'
  | 'check.duration_tolerance'
  | 'meta.title_max'
  | 'meta.description_max'
  | 'meta.hashtags'
  | 'policy.batch.tts_lines'
  | 'policy.batch.images'
  | 'policy.paid_api.per_call_usd'
  | 'policy.budget_warn_ratio'
  | `gpu.vram_budget_gb.${string}`
  | 'gpu.vram_total_gb'
  | 'autopilot.enabled'
  | 'autopilot.paused'
  | 'autopilot.competitors'
  | 'autopilot.pillars'
  | 'autopilot.workflows'
  | 'autopilot.max_per_day'
  | 'autopilot.min_score'
  | 'autopilot.duration_waive_ratio'
  | 'autopilot.work_window'
  | 'autopilot.budget_share'
  | 'autopilot.daily_tokens'
  | 'publish.platforms'
  | 'publish.slots'
  | 'publish.timezone'
  | 'publish.veto_hours';


export interface WorkflowManifest {
  id: string; version: string; title: string; description: string;
  app_api: string;                          // semver range
  upstream?: { hyperframes_workflow: string; hyperframes_version: string };
  output_profiles: string[];                // cho phép; phần tử đầu là mặc định
  requires: string[];                       // capability bắt buộc
  optional?: string[];
  brief?: { questions: string[] };          // câu hỏi thêm cho router khi chốt brief (mục 3.0)
  scripts?: { id: string; command: string; args_schema?: object; writes?: string[] }[];
  config_defaults?: Record<string, unknown>; // tầng cấu hình `workflow` (D3 mục 7.1): chỉ khóa cho phép ở tầng channel hoặc video
  steps: StepDecl[];                        // không gồm brief (brief là pha trước workflow)
}

export type StepLibraryId = 'design-system' | 'script' | 'storyboard' | 'cast' | 'voice' | 'assets' | 'frame-build'
  | 'animatic' | 'captions' | 'music' | 'look' | 'effects' | 'overlays' | 'lipsync' | 'finalize' | 'publish-meta' | 'render';

export interface StepDecl {
  id: string;                               // duy nhất trong workflow
  uses: StepLibraryId;
  title: string;
  after?: string[];                         // phụ thuộc; mặc định = bước trước
  params?: Record<string, unknown>;         // theo schema params của bước (mục 2)
  refine?: { enabled: boolean; rubric: string; min_rounds?: number; max_rounds?: number; threshold?: number };
  approval?: { required: boolean; summary_template?: string };
  gate?: GateDecl[];                        // thêm vào gate mặc định của bước
  skip_if?: { config: ConfigKey; equals: unknown } | { phase_before: 'M3' }; // điều kiện bỏ qua; ngữ pháp duy nhất
}

export type GateDecl =
  | { kind: 'artifact_valid'; path: string }
  | { kind: 'graph_fresh'; nodes: string }  // ví dụ 'audio.line:*'
  | { kind: 'approved'; step: string }
  | { kind: 'script'; script: string }      // script trả exit 0 = qua
  | { kind: 'objective'; check: string; params?: Record<string, unknown> };   // mục 4.2

export interface Rubric { id: string; version: number; scale: 10;
  criteria: { id: string; weight: number; prompt: string }[];   // Σ weight = 1
  severity_rules: string; }

export interface FramePacket {
  video_id: VideoId; frame: Frame; scene: Scene;
  lines: Line[]; timing: { start_ms: Ms; duration_ms: Ms };
  design_system: RelPath;                 // frame.md
  blueprint?: { id: string; path: RelPath; vars: Record<string, string> };
  assets: { asset_id: AssetId; file: RelPath; width: number; height: number; alpha: boolean }[];
  output_path: RelPath;                   // compositions/frames/<fr>.html — phạm vi ghi duy nhất
  rules: string[];                        // từ hồ sơ kênh: font, màu, vùng an toàn…
  pinned_delta?: ManualDelta;             // khi sinh lại có áp lại chỉnh tay
}


export interface SessionContext {
  session_id: SessionId; kind: 'main' | 'frame' | 'producer' | 'critic';
  channel_dir: string; video_id?: VideoId; frame_id?: FrameId;
  allowed_paths?: RelPath[];          // phạm vi ghi (frame/producer)
  read_only_videos?: VideoId[];       // đọc chéo video (shorts từ video dài)
}

export type ToolResult<T> =
  | { ok: true; data: T; job_id?: string }          // job_id khi việc chạy nền
  | { ok: false; error: { code: string; message: string; details?: unknown; retryable: boolean } };

export interface CapabilityContract<I, O> { id: string; version: string; input: I; output: O; resource: ResourceClass; cacheable: boolean; }
export type ResourceClass = 'gpu-heavy' | 'gpu-light' | 'cpu' | 'network';

// voice.profile
export interface VoiceProfileInput { name: string; language: Lang; ref_audio: RelPath; emotions?: Record<string, RelPath>; }
export interface VoiceProfileOutput { voice_id: VoiceId; files: RelPath[]; }

// voice.design (033): instruct theo từ vựng OmniVoice, ví dụ "female, young adult, moderate pitch"
export interface VoiceDesignInput { name: string; language: Lang; instruct: string; sample_text: string; seed?: number; }
// đầu ra như VoiceProfileOutput; profile.json thêm design: { instruct, seed }, suggested_for?

// tts.synthesize (một line mỗi lần gọi provider)
export interface TtsInput { text: string; language: Lang; voice_id: VoiceId; emotion?: string; speed?: number; }
export interface TtsOutput { file: RelPath; duration_ms: Ms; sample_rate: 48000; }

// asr.align
export interface AsrAlignInput { audio: RelPath; language: Lang; expected_text: string; }
export interface AsrAlignOutput { words: { i: number; text: string; start_ms: Ms; end_ms: Ms; conf?: number }[]; transcript: string; wer: number; }

// image.generate / image.edit
export interface ImageGenerateInput { prompt: string; negative_prompt?: string; width: number; height: number; transparent?: boolean;
  reference_asset_ids?: AssetId[]; look?: string; seed?: number; steps?: number; }
export interface ImageEditInput { source_asset_id: AssetId; instruction: string; mask_asset_id?: AssetId; reference_asset_ids?: AssetId[]; seed?: number; }
export interface ImageOutput { file: RelPath; width: number; height: number; alpha: boolean; seed: number; }

// image.remove_bg
export interface RemoveBgInput { source_asset_id: AssetId; subject: 'person' | 'object'; }

// text.generate / text.review (chỉ Workflow Engine)
export interface TextGenerateInput { role: 'primary' | 'aux'; messages: { role: 'system' | 'user' | 'assistant'; content: string }[];
  max_tokens: number; temperature?: number; response_format?: 'text' | 'json'; }
export interface TextGenerateOutput { text: string; usage: { input: number; output: number }; cost_usd: number; model: string; }
export interface TextReviewInput { artifact_text: string; rubric: Rubric; brief: string; prior_issues?: ReviewRound['issues']; }
export interface TextReviewOutput { score: number; criteria: ReviewRound['criteria']; issues: ReviewRound['issues']; usage: TextGenerateOutput['usage']; cost_usd: number; model: string; }

// lipsync.cues
export interface LipsyncInput { audio: RelPath; fps: number; thresholds?: { half: number; open: number }; }

// render.video
export interface RenderInput { mode: 'draft' | 'release'; output_profile: string; }

export interface VideoStateSummary { video_id: VideoId; phase: VideoState['phase']; workflow: VideoState['workflow'];
  current_step?: string; steps: { id: string; title: string; status: StepState['status']; refine?: StepState['refine'] }[];
  pending_approvals: ApprovalId[]; owner: VideoState['owner']; budget: VideoState['budget']; }
export interface NodeStatus { key: string; type: string; status: 'fresh' | 'stale' | 'missing' | 'pinned' | 'pinned_stale' | 'failed' | 'external_change' | 'orphan';
  reason?: string; decision_required?: boolean; }
export interface PlannedJob { kind: string; targets: string[]; engine?: string; phase: number; est_ms: number; est_cost_usd: number; from_cache: boolean; }
export interface PlanEstimate { total_ms: number; total_cost_usd: number; jobs_count: number; cached_count: number; }
// graph.plan trả { jobs: PlannedJob[]; estimate: PlanEstimate }

export interface ProviderManifest {
  id: string; version: string; capabilities: string[]; contract_versions: Record<string, string>;
  runtime: 'python-worker' | 'comfyui' | 'node' | 'cloud' | 'agent-runtime';
  engine?: string; resource: ResourceClass; languages?: Lang[]; models?: string[];
  install_profile: 'minimal' | 'standard' | 'full'; cost: { kind: 'free' | 'per_token' | 'per_image' | 'per_second' };
  limits?: Record<string, number>; health: { method: string; timeout_ms: number };
  secrets?: string[]; network?: string[]; app_api: string;
  defaults?: Record<string, unknown>;              // tham số mặc định của model (mục 9.2)
}

export interface JobInfo {
  id: string; kind: string;               // capability id hoặc 'graph.build' | 'render' | 'script' | 'download'
  video_id?: VideoId; status: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled' | 'partial';
  progress: { done: number; total: number; message?: string };
  engine?: string; priority: 0 | 1 | 2;   // 2 = đang chặn điểm duyệt
  attempts: number; max_attempts: number; // mặc định 3 (1 lần chạy + 2 lần thử lại)
  created_at: Iso8601; started_at?: Iso8601; finished_at?: Iso8601;
  result?: unknown; error?: { code: string; message: string; retryable: boolean };
  children?: string[];                    // job con (ví dụ một job/line)
}


export interface AgentRuntime {
  id: string;                                   // 'claude-agent-sdk'
  authStatus(): Promise<{ ok: boolean; method: 'claude-plan' | 'api-key' | 'none'; detail?: string }>;
  openSession(opts: SessionOptions): Promise<AgentSession>;
}

export interface SessionOptions {
  kind: 'main' | 'frame' | 'producer' | 'critic';
  context: SessionContext;                      // D4 mục 2.2
  model: string;                                // theo bảng mục 2
  systemAppend: string;                         // quy tắc app (mục 6) + chỉ dẫn theo kind
  plugins: string[];                            // đường dẫn tuyệt đối thư mục plugin (mục 3)
  tools: ToolPolicy;                            // mục 4
  resume?: string;                              // id phiên để tiếp tục (chỉ 'main')
  maxTurns?: number; budgetTokens?: number;
  telemetry: { traceparent: string };           // D11
}

export interface AgentSession {
  id: string;
  send(message: UserMessage): AsyncIterable<AgentEvent>;
  interrupt(): Promise<void>;
  close(): Promise<void>;
}

export type UserMessage = { text: string; attachments?: { path: string; mime: string }[]; context_refs?: ContextRef[] };
export type ContextRef = { kind: 'frame' | 'time' | 'element' | 'caption_group'; id?: string; time_ms?: Ms };

export type AgentEvent =
  | { type: 'text_delta'; text: string }
  | { type: 'tool_call'; id: string; name: string; input: unknown }
  | { type: 'tool_result'; id: string; ok: boolean; summary: string }
  | { type: 'usage'; input_tokens: number; output_tokens: number; cost_usd?: number }
  | { type: 'done'; stop_reason: string }
  | { type: 'error'; code: string; message: string };

export type ToolPolicy = { allowed: string[]; readRoots: string[] };   // allowed: tên tool MCP + built-in theo mục 4; readRoots: thư mục cho Read/Glob/Grep


export interface MusicManifest extends Versioned {   // schema_version 1
  tracks: MusicTrack[];
}

export interface MusicTrack {
  id: MusicTrackId; kind: 'music' | 'sfx';
  file: RelPath; original_name: string; hash: Sha256;
  title?: string; artist?: string;
  source?: string; url?: string;             // ví dụ "YouTube Audio Library", "Pixabay"
  attribution?: string;                      // văn bản ghi công nguyên văn, nếu bài yêu cầu
  tags: string[];                            // thể loại, tâm trạng, nhạc cụ (chữ thường)
  description?: string;
  analysis: {
    duration_ms: Ms; sample_rate: number; channels: number;
    bpm?: number; bpm_confidence?: number;
    energy: number;                          // 0–1, RMS trung bình chuẩn hóa
    energy_curve: number[];                  // RMS mỗi 1 giây, 0–1
    loudness_lufs: number;
    loop_points?: { start_ms: Ms; end_ms: Ms }[];
    silence_head_ms: Ms; silence_tail_ms: Ms;
  };
  embedding?: { model: string; vector_file: RelPath };   // M2, '.index/<track_id>.npy' tương đối với thư mục kho
  added_at: Iso8601; used_in: VideoId[];
}

export interface MusicFindInput {
  query?: string;                       // mô tả tự nhiên hoặc từ khóa
  tags?: string[];                      // phải có tất cả
  bpm?: { min?: number; max?: number };
  energy?: { min?: number; max?: number };
  min_duration_ms?: Ms;
  exclude_ids?: MusicTrackId[];
  limit?: number;                       // mặc định 5
}
export interface MusicFindOutput { results: { track_id: MusicTrackId; score: number; reasons: string[] }[] }
