// GENERATED by scripts/gen-contracts.mjs from docs/04-spec-capability-gateway.md mục 2.2–2.3 — DO NOT EDIT. Sửa nguồn rồi chạy lại.
import type { VideoId, FrameId, RelPath, SessionId } from '../domain/d3';

export interface SessionContext {
  session_id: SessionId; kind: 'main' | 'frame' | 'producer' | 'critic';
  channel_dir: string; video_id?: VideoId; frame_id?: FrameId;
  allowed_paths?: RelPath[];          // phạm vi ghi (frame/producer)
  read_only_videos?: VideoId[];       // đọc chéo video (shorts từ video dài)
}

export type ToolResult<T> =
  | { ok: true; data: T; job_id?: string }          // job_id khi việc chạy nền
  | { ok: false; error: { code: string; message: string; details?: unknown; retryable: boolean } };
